import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/main_ui/NavBar";
import { Footer } from "./components/main_ui/Footer";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {/* Full height layout */}
          <div className="min-h-screen flex flex-col">
            {/* Navbar stays on top */}
            <Navbar />

            {/* Main content grows */}
            <main className="flex-1 pt-20">
              {children}
            </main>

            {/* Footer stays at bottom */}
            <Footer />
          </div>

          <Toaster position="top-center" />
        </SessionProvider>
      </body>
    </html>
  )
}

